<a id='top'></a>

# Preliminary Test of Listen-Attend-Spell Model on Single Words

### Tests:
* [Librispeech on top 200 words in GigaSpeech](#LibriSpeech_on_GigaSpeech200)
* [Librispeech CTC model on top 200 words in GigaSpeech](#LibriSpeech_CTC_on_GigaSpeech200)
* [GigaSpeech on top 200 words in GigaSpeech](#GigaSpeech_on_GigaSpeech200)
* [GigaSpeech on English Consistent Confusion Corpus](#GigaSpeech_on_EnglishCCC)
* [GigaSpeech top 10 guesses on GigaSpeech 200](#GigaSpeech_Top_10)

##### To Try:
* GigaSpeeh CTC model

___ 

Import Modules

In [2]:
import pandas as pd 
import numpy as np

<a id='LibriSpeech_on_GigaSpeech200'></a>

[Top](#top)
___
### Look at Librispeech model performance on top 200 Gigaspeech words

This model was trained on the Librispeech clean 100hr set, and achieved an average word error of 18% on the librispeech clean test set.

In [2]:
path = '../result/single_word_decode_test_output.csv' # test and dev are same set here 
df = pd.read_csv(path, sep='\t')

Looking at correct single word guesses:

In [3]:
good_guesses = len(df[df['hyp'] == df['truth']]) 
percent_right = 100 * good_guesses / len(df)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
df[df['hyp'] == df['truth']]

57 exact guesses; 28.5% correct

     idx        hyp      truth
1      1        AND        AND
2      2         TO         TO
8      8        YOU        YOU
10    10         IT         IT
13    13         SO         SO
14    14       THIS       THIS
15    15         WE         WE
16    16        BUT        BUT
27    27       LIKE       LIKE
28    28       WHAT       WHAT
33    33        ONE        ONE
34    34         OR         OR
38    38         DO         DO
39    39       FROM       FROM
40    40      THERE      THERE
41    41       JUST       JUST
43    43       YOUR       YOUR
46    46         ME         ME
48    48       WHEN       WHEN
51    51      WHICH      WHICH
52    52        HER        HER
58    58       THEN       THEN
64    64        NOW        NOW
66    66        HOW        HOW
68    68    BECAUSE    BECAUSE
73    73     REALLY     REALLY
82    82      RIGHT      RIGHT
83    83       HERE       HERE
86    86       WELL       WELL
87    87        SEE        SEE
90    90      WHERE      WHERE
96    96        SAY        SAY
98    98       YEAH       YEAH
102  102      FIRST      FIRST
110  110  SOMETHING  SOMETHING
116  116       DOWN       DOWN
122  122    THROUGH    THROUGH
128  128     BEFORE     BEFORE
134  134        WHY        WHY
135  135      AGAIN      AGAIN
138  138        DAY        DAY
146  146      STILL      STILL
157  157       PART       PART
163  163       SUCH       SUCH
165  165     ALWAYS     ALWAYS
166  166       DOES       DOES
168  168       NEXT       NEXT
169  169        YES        YES
170  170      POINT      POINT
172  172       SORT       SORT
186  186       AWAY       AWAY
188  188   QUESTION   QUESTION
189  189       FEEL       FEEL
192  192       OKAY       OKAY
193  193      WHILE      WHILE
196  196       EACH       EACH
197  197       SURE       SURE

Example of bad guesses

In [4]:
df[df['hyp'] != df['truth']].head(50)

    idx        hyp   truth
0     0      <unk>     THE
3     3        AND      OF
4     4      <unk>       A
5     5        BUT    THAT
6     6        AND      IN
7     7         OH       I
9     9                 IS
11   11        WHY     WAS
12   12         SO     FOR
17   17        WAS    WITH
18   18       FIND      ON
19   19        HAS    HAVE
20   20        SEE      HE
21   21                 AS
22   22        DAY      BE
23   23      THERE     ARE
24   24       OKAY    THEY
25   25       YEAH     NOT
26   26        AND      AT
29   29         NO    KNOW
30   30    BECAUSE     HIS
31   31        BUT     ALL
32   32        NOW   ABOUT
35   35        HOW     HAD
36   36                 IF
37   37        NOW      MY
42   42       OKAY     CAN
44   44       WELL      BY
45   45        BUT      AH
47   47        BUT      AN
49   49       WHAT    WERE
50   50   GIVE YOU  PEOPLE
53   53        SAY     SHE
54   54         IT     OUT
55   55  THANK YOU   THINK
56   56       WHAT   WOULD
57   57                 UP
59   59      THERE     OUR
60   60      <unk>     WHO
61   61      THERE   THEIR
62   62       THEN    THEM
63   63      NORTH    MORE
65   65       SAID    SOME
67   67        NOW    VERY
69   69       WELL    WILL
70   70       THEN    BEEN
71   71        AND      UM
72   72        AND   GOING
74   74       WELL      NO
75   75       OKAY    TIME

<a id='LibriSpeech_CTC_on_GigaSpeech200'></a>

[Top](#top)
___
### LibriSpeech CTC model on GigaSpeech 200 words

This model was trained on the Librispeech clean 100hr set using connectionist temporal classification instead of the encoder with attention method. This model's word error was 30% on the librispeech clean dev set.

In [5]:
path = '../result/lib_ctc_single_word_early/single_word_decode_test_output.csv' # test and dev are same set here 
cdf = pd.read_csv(path, sep='\t')

Looking at correct single word guesses:

In [6]:
good_guesses = len(cdf[cdf['hyp'] == cdf['truth']]) 
percent_right = 100 * good_guesses / len(cdf)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
cdf[cdf['hyp'] == cdf['truth']]

18 exact guesses; 9.0% correct

     idx     hyp   truth
1      1     AND     AND
13    13      SO      SO
25    25     NOT     NOT
27    27    LIKE    LIKE
28    28    WHAT    WHAT
36    36      IF      IF
43    43    YOUR    YOUR
46    46      ME      ME
51    51   WHICH   WHICH
74    74      NO      NO
98    98   <unk>   <unk>
102  102   FIRST   FIRST
124  124    LOOK    LOOK
128  128  BEFORE  BEFORE
131  131   GREAT   GREAT
157  157    PART    PART
163  163    SUCH    SUCH
185  185    DONE    DONE

Examples of bad guesses

In [7]:
cdf[cdf['hyp'] != cdf['truth']].head(50)

    idx          hyp   truth
0     0           UP     THE
2     2          TIP      TO
3     3          AND      OF
4     4           IT       A
5     5      THAT UP    THAT
6     6          AND      IN
7     7          BUT       I
8     8          YET     YOU
9     9           AS      IS
10   10         IT'S      IT
11   11         WHAT     WAS
12   12        <unk>     FOR
14   14           IN    THIS
15   15  RIGHT IT IT      WE
16   16        NOT A     BUT
17   17        WHERE    WITH
18   18         GOOD      ON
19   19          HAS    HAVE
20   20          PUT      HE
21   21         ELSE      AS
22   22           AN      BE
23   23        <unk>     ARE
24   24         LIKE    THEY
26   26           ET      AT
29   29           NO    KNOW
30   30            I     HIS
31   31        BUILT     ALL
32   32          NOT   ABOUT
33   33        WHITE     ONE
34   34         WORK      OR
35   35           GO     HAD
37   37          NOT      MY
38   38          ILL      DO
39   39           AN    FROM
40   40       IF ARE   THERE
41   41        <unk>    JUST
42   42        <unk>     CAN
44   44        <unk>      BY
45   45                   AH
47   47          BUT      AN
48   48         WENT    WHEN
49   49         WHAT    WERE
50   50    GENTLEMAN  PEOPLE
52   52          PUT     HER
53   53       SHOULD     SHE
54   54        DON'T     OUT
55   55       PICKED   THINK
56   56         LIKE   WOULD
57   57        <unk>      UP
58   58           AN    THEN

<a id='GigaSpeech_on_GigaSpeech200'></a>

[Top](#top)
___
### GigaSpeech Model performance on top 200 GigaSpeech words

*this is a mid-training checkpoint, not fully trained!!*

In [2]:
# path = '../results/gigaspeech_single_word_early/single_word_decode_test_output.csv' # test and dev are same set here 
# path = '../result/gigaspeech_word_45_wer/single_word_decode_dev_output.csv'
path = '../result/gigaspeech_single_word_decode_dev_output.csv'
gdf = pd.read_csv(path, sep='\t')

In [3]:
gdf.rename(columns={'idx': 'freq_rank'}, inplace=True)

Good guesses by model

In [4]:
good_guesses = len(gdf[gdf['hyp'] == gdf['truth']]) 
percent_right = 100 * good_guesses / len(gdf)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
gdf[gdf['hyp'] == gdf['truth']]

37 exact guesses; 18.5% correct

     freq_rank        hyp      truth
1            1        AND        AND
2            2         TO         TO
13          13         SO         SO
15          15         WE         WE
16          16        BUT        BUT
21          21         AS         AS
27          27       LIKE       LIKE
28          28       WHAT       WHAT
38          38         DO         DO
39          39       FROM       FROM
41          41       JUST       JUST
48          48       WHEN       WHEN
55          55      THINK      THINK
64          64        NOW        NOW
68          68    BECAUSE    BECAUSE
82          82      RIGHT      RIGHT
86          86       WELL       WELL
87          87        SEE        SEE
98          98       YEAH       YEAH
102        102      FIRST      FIRST
104        104       OVER       OVER
110        110  SOMETHING  SOMETHING
131        131      GREAT      GREAT
134        134        WHY        WHY
135        135      AGAIN      AGAIN
146        146      STILL      STILL
155        155     AROUND     AROUND
156        156       LAST       LAST
157        157       PART       PART
163        163       SUCH       SUCH
169        169        YES        YES
186        186       AWAY       AWAY
188        188   QUESTION   QUESTION
192        192       OKAY       OKAY
195        195     TWENTY     TWENTY
196        196       EACH       EACH
197        197       SURE       SURE

Examples of bad guesses

In [5]:
gdf[gdf['hyp'] != gdf['truth']].head(50)

    freq_rank        hyp   truth
0           0       YEAH     THE
3           3         AT      OF
4           4      <unk>       A
5           5        BUT    THAT
6           6        AND      IN
7           7        HEY       I
8           8       YEAH     YOU
9           9         AS      IS
10         10        AND      IT
11         11       WHAT     WAS
12         12         SO     FOR
14         14        YES    THIS
17         17       WEST    WITH
18         18  ALL RIGHT      ON
19         19      <unk>    HAVE
20         20       OKAY      HE
22         22          I      BE
23         23      THERE     ARE
24         24       WELL    THEY
25         25       YEAH     NOT
26         26         OH      AT
29         29         NO    KNOW
30         30      <unk>     HIS
31         31         OH     ALL
32         32        AND   ABOUT
33         33       LIKE     ONE
34         34        ARE      OR
35         35       OKAY     HAD
36         36        YES      IF
37         37      NIGHT      MY
40         40    BECAUSE   THERE
42         42       OKAY     CAN
43         43      <unk>    YOUR
44         44        HEY      BY
45         45        BUT      AH
46         46         NO      ME
47         47        YES      AN
49         49       WHAT    WERE
50         50   YOU KNOW  PEOPLE
51         51       MUCH   WHICH
52         52          I     HER
53         53         SO     SHE
54         54          I     OUT
56         56      RIGHT   WOULD
57         57         AH      UP
58         58      <unk>    THEN
59         59       OVER     OUR
60         60         OH     WHO
61         61        THE   THEIR
62         62       THEN    THEM

<a id='GigaSpeech_on_EnglishCCC'></a>

[Top](#top)
___
### GigaSpeech Model performance on top EnglishCCC words


Some of the target words of the English Consistent Confusion Corpus words are out of the GigaSpeech vocabulary, so we will only look at words the model knows.

In [12]:
path = '../result/english_ccc_single_word_decode_test_output.csv'
ecccdf = pd.read_csv(path, sep='\t')

In [16]:
len(ecccdf)

3207

Looking at correct single word guesses:

In [13]:
good_guesses = ecccdf[(ecccdf['hyp'] == ecccdf['truth']) &  (ecccdf['truth'] != '<unk>')]
percent_right = 100 * len(good_guesses) / len(ecccdf)
print(f"{len(good_guesses)} exact guesses; {round(percent_right,2)}% correct")
good_guesses

581 exact guesses; 18.12% correct

       idx       hyp     truth
4        4   BECAUSE   BECAUSE
10      10      FAME      FAME
16      16  RECEIVED  RECEIVED
19      19   HEARING   HEARING
23      23     CLASS     CLASS
...    ...       ...       ...
3186  3186    CRISIS    CRISIS
3190  3190     VISIT     VISIT
3196  3196      LIKE      LIKE
3198  3198     SORRY     SORRY
3199  3199       DAD       DAD

[581 rows x 3 columns]

392

Examples of incorrect guesses

In [14]:
ecccdf[(ecccdf['hyp'] != ecccdf['truth']) &  (ecccdf['truth'] != '<unk>')].head(50)

    idx        hyp      truth
2     2      <unk>     STANCE
3     3      <unk>     REMOTE
6     6     INSIDE    INSIGHT
7     7      <unk>     RADIUS
11   11    A <unk>      ACUTE
12   12   CHILDREN   CHILDISH
13   13         BY      BUYER
14   14      <unk>      GUEST
15   15      <unk>       DRUG
17   17       MARK     MARKED
18   18     FORMER     FORMAL
20   20      <unk>    CAUTION
22   22      <unk>      CHESS
24   24     GROWTH      GROSS
25   25      <unk>     HUMBLE
26   26       MEET       NEAT
30   30      <unk>        JAW
32   32      <unk>    SAILING
33   33      <unk>      NAVAL
34   34      <unk>     PATROL
36   36      <unk>      CHESS
37   37      <unk>      FAIRY
41   41      <unk>       JUNK
44   44       HERE        ERA
45   45       PUSH     PUSHED
46   46       THAT       BOAT
47   47                  HOOK
48   48      <unk>  MOONLIGHT
49   49  THE <unk>       GENE
53   53      <unk>        HUT
55   55      <unk>       PINE
57   57      <unk>      COUGH
58   58      <unk>     POWDER
59   59      <unk>      ASSET
60   60       HERE       HAIR
61   61      <unk>      CLOTH
62   62      <unk>     WOODEN
63   63       PLAY       PLEA
65   65      FIRST    FIRSTLY
66   66      <unk>      CHARM
70   70        FAT       THAT
71   71        SHE      CHEEK
72   72      <unk>       ROAR
73   73        AND       EARN
74   74      <unk>     CALMLY
75   75        BUT       WHAT
76   76      <unk>      FRAUD
77   77   KILL HER     KILLER
78   78       FIVE       BITE
80   80      <unk>     SELDOM

<a id='GigaSpeech_Top_10'></a>

[Top](#top) 
___

## GigaSpeech Top 10 Decode

In [3]:
path = '../result/gigaspeech_single_word_top_N_dev_beam-10-0.csv'
top_10 = pd.read_csv(path, sep='\t')

In [4]:
top_10

        idx  beam         hyp  truth
0       The     0        YEAH    THE
1       The     1    AND YEAH    THE
2       The     2          SO    THE
3       The     3     AS YEAH    THE
4       The     4         BUT    THE
...     ...   ...         ...    ...
1995  Gonna     5       <unk>  GONNA
1996  Gonna     6        THEN  GONNA
1997  Gonna     7         THE  GONNA
1998  Gonna     8          IF  GONNA
1999  Gonna     9  <unk> THAT  GONNA

[2000 rows x 4 columns]

In [31]:
good_guesses = top_10[(top_10['hyp'] == top_10['truth']) & (top_10['beam']<=0)]
percent_right = 100 * len(good_guesses) / len(top_10.truth.unique())
print(f"{len(good_guesses)} exact guesses; {round(percent_right,2)}% correct")
good_guesses

37 exact guesses; 18.5% correct

            idx  beam        hyp      truth
10          And     0        AND        AND
20           To     0         TO         TO
130          So     0         SO         SO
150          We     0         WE         WE
160         But     0        BUT        BUT
210          As     0         AS         AS
270        Like     0       LIKE       LIKE
280        What     0       WHAT       WHAT
380          Do     0         DO         DO
390        From     0       FROM       FROM
410        Just     0       JUST       JUST
480        When     0       WHEN       WHEN
550       Think     0      THINK      THINK
640         Now     0        NOW        NOW
680     Because     0    BECAUSE    BECAUSE
820       Right     0      RIGHT      RIGHT
860        Well     0       WELL       WELL
870         See     0        SEE        SEE
980        Yeah     0       YEAH       YEAH
1020      First     0      FIRST      FIRST
1040       Over     0       OVER       OVER
1100  Something     0  SOMETHING  SOMETHING
1310      Great     0      GREAT      GREAT
1340        Why     0        WHY        WHY
1350      Again     0      AGAIN      AGAIN
1460      Still     0      STILL      STILL
1550     Around     0     AROUND     AROUND
1560       Last     0       LAST       LAST
1570       Part     0       PART       PART
1630       Such     0       SUCH       SUCH
1690        Yes     0        YES        YES
1860       Away     0       AWAY       AWAY
1880   Question     0   QUESTION   QUESTION
1920       Okay     0       OKAY       OKAY
1950     Twenty     0     TWENTY     TWENTY
1960       Each     0       EACH       EACH
1970       Sure     0       SURE       SURE

In [34]:
top_match_guesses = top_10[(top_10['hyp'] == top_10['truth'])]
percent_right = 100 * len(top_match_guesses) / len(top_10.truth.unique())
print(f"{len(top_match_guesses)} matched guesses; {round(percent_right,2)}% correct")
top_match_guesses

90 matched guesses; 45.0% correct

         idx  beam     hyp   truth
10       And     0     AND     AND
20        To     0      TO      TO
47         A     7       A       A
51      That     1    THAT    THAT
71         I     1       I       I
...      ...   ...     ...     ...
1920    Okay     0    OKAY    OKAY
1935   While     5   WHILE   WHILE
1950  Twenty     0  TWENTY  TWENTY
1960    Each     0    EACH    EACH
1970    Sure     0    SURE    SURE

[90 rows x 4 columns]

In [33]:
close_guesses = top_10[top_10.apply(lambda x: x.truth in x.hyp, axis=1)]
percent_right = 100 * len(close_guesses.truth.unique()) / len(top_10.truth.unique())
print(f"{len(close_guesses)} included guesses; {round(percent_right,2)}% correct")
close_guesses

274 included guesses; 49.0% correct

       idx  beam         hyp truth
10     And     0         AND   AND
11     And     1     AND AND   AND
12     And     2      AND AH   AND
13     And     3     AND HER   AND
14     And     4      AND AT   AND
...    ...   ...         ...   ...
1974  Sure     4    SURE FOR  SURE
1975  Sure     5     SURE SO  SURE
1977  Sure     7     SURE IT  SURE
1978  Sure     8  SURE <unk>  SURE
1979  Sure     9     SURE OF  SURE

[274 rows x 4 columns]

In [21]:
len(close_guesses.truth.unique())

98