<a id='top'></a>

# Preliminary Test of Listen-Attend-Spell Model on Single Words

### Tests:
* [Librispeech on top 200 words in GigaSpeech](#LibriSpeech_on_GigaSpeech200)
* [Librispeech LAS top 10 on GigaSpeech](#LibriSpeech_LAS_Top_10)
* [Librispeech CTC model on top 200 words in GigaSpeech](#LibriSpeech_CTC_on_GigaSpeech200)
* [GigaSpeech on top 200 words in GigaSpeech](#GigaSpeech_on_GigaSpeech200)
* [GigaSpeech on English Consistent Confusion Corpus](#GigaSpeech_on_EnglishCCC)
* [GigaSpeech top 10 guesses on GigaSpeech 200](#GigaSpeech_Top_10)

##### To Try:
* GigaSpeeh CTC model

___ 

Import Modules

In [1]:
import pandas as pd 
import numpy as np

<a id='LibriSpeech_on_GigaSpeech200'></a>

[Top](#top)
___
### Look at Librispeech model performance on top 200 Gigaspeech words

This model was trained on the Librispeech clean 100hr set, and achieved an average word error of 18% on the librispeech clean test set.

In [2]:
path = '../result/librispeech_single_word_decode_dev_output.csv' # test and dev are same set here 
df = pd.read_csv(path, sep='\t')

Looking at correct single word guesses:

In [3]:
good_guesses = len(df[df['hyp'] == df['truth']]) 
percent_right = 100 * good_guesses / len(df)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
df[df['hyp'] == df['truth']]

12 exact guesses; 6.0% correct

     idx    hyp  truth
1      1    AND    AND
28    28   WHAT   WHAT
36    36     IF     IF
51    51  WHICH  WHICH
64    64    NOW    NOW
74    74     NO     NO
98    98  <unk>  <unk>
124  124   LOOK   LOOK
144  144  EVERY  EVERY
163  163   SUCH   SUCH
164  164   FIND   FIND
198  198    LET    LET

Example of bad guesses

In [4]:
df[df['hyp'] != df['truth']].head(50)

    idx                                  hyp   truth
0     0                               IT YET     THE
2     2                                <unk>      TO
3     3                                   AS      OF
4     4                                            A
5     5                             BUT THAT    THAT
6     6                                           IN
7     7                                <unk>       I
8     8                                   YO     YOU
9     9                                 IT'S      IS
10   10                                 IT'S      IT
11   11                               WHAT'S     WAS
12   12                              FLORIDA     FOR
13   13                               ITSELF      SO
14   14                                         THIS
15   15                                <unk>      WE
16   16                                  NOT     BUT
17   17                              WOULDST    WITH
18   18                                  BUT      ON
19   19                             CAN'T MY    HAVE
20   20                                           HE
21   21                                 IT'S      AS
22   22                                ABOUT      BE
23   23                                EARTH     ARE
24   24                                 THAT    THEY
25   25                                  YET     NOT
26   26                                 THEN      AT
27   27                                  LET    LIKE
29   29                                   NO    KNOW
30   30                                   AS     HIS
31   31                            CAN'T GET     ALL
32   32                              AND NOT   ABOUT
33   33                                 WHAT     ONE
34   34                            THE <unk>      OR
35   35                                <unk>     HAD
37   37                              NOT NOT      MY
38   38                                DON'T      DO
39   39                                SPENT    FROM
40   40                                 THAT   THERE
41   41                                  GAS    JUST
42   42                                 DEAD     CAN
43   43                               YOU'RE    YOUR
44   44                          NIGHT NIGHT      BY
45   45                                   IF      AH
46   46                                 NOTE      ME
47   47                                  AND      AN
48   48                                 WENT    WHEN
49   49                          <unk> <unk>    WERE
50   50                          DON'T DON'T  PEOPLE
52   52                                  PIT     HER
53   53  COULDN'T COULDN'T COULDN'T COULDN'T     SHE

<a id='LibriSpeech_LAS_Top_10'></a>

[Top](#top)
___
## LibriSpeech LAS model 10 Best on GigaSpeech 200 words

In [5]:
path = '../result/librispeech_single_word_top_N_dev_beam-10-0.csv'
lib_nbest = pd.read_csv(path, sep='\t')

In [6]:
good_guesses = lib_nbest[(lib_nbest['hyp'] == lib_nbest['truth']) & (lib_nbest['beam']==0)]
percent_right = 100 * len(good_guesses) / len(lib_nbest.truth.unique())
print(f"{len(good_guesses)} exact guesses; {round(percent_right,2)}% correct")
good_guesses

12 exact guesses; 6.09% correct

        idx  beam    hyp  truth
10      And     0    AND    AND
280    What     0   WHAT   WHAT
360      If     0     IF     IF
510   Which     0  WHICH  WHICH
640     Now     0    NOW    NOW
740      No     0     NO     NO
980    Yeah     0  <unk>  <unk>
1240   Look     0   LOOK   LOOK
1440  Every     0  EVERY  EVERY
1630   Such     0   SUCH   SUCH
1640   Find     0   FIND   FIND
1980    Let     0    LET    LET

In [7]:
top_match_guesses = lib_nbest[(lib_nbest['hyp'] == lib_nbest['truth'])]
percent_right = 100 * len(top_match_guesses) / len(lib_nbest.truth.unique())
print(f"{len(top_match_guesses)} matched guesses; {round(percent_right,2)}% correct")
top_match_guesses

34 matched guesses; 17.26% correct

            idx  beam        hyp      truth
10          And     0        AND        AND
62           In     2         IN         IN
96           Is     6         IS         IS
101          It     1         IT         IT
112         Was     2        WAS        WAS
162         But     2        BUT        BUT
254         Not     4        NOT        NOT
280        What     0       WHAT       WHAT
291        Know     1       KNOW       KNOW
360          If     0         IF         IF
434        Your     4       YOUR       YOUR
481        When     1       WHEN       WHEN
510       Which     0      WHICH      WHICH
624        Them     4       THEM       THEM
640         Now     0        NOW        NOW
740          No     0         NO         NO
801        Said     1       SAID       SAID
980        Yeah     0      <unk>      <unk>
1001       Much     1       MUCH       MUCH
1102  Something     2  SOMETHING  SOMETHING
1240       Look     0       LOOK       LOOK
1264       Most     4       MOST       MOST
1440      Every     0      EVERY      EVERY
1548        Put     8        PUT        PUT
1630       Such     0       SUCH       SUCH
1640       Find     0       FIND       FIND
1666       Does     6       DOES       DOES
1692        Yes     2        YES        YES
1851       Done     1       DONE       DONE
1936      While     6      WHILE      WHILE
1961       Each     1       EACH       EACH
1976       Sure     6       SURE       SURE
1980        Let     0        LET        LET
1996      Gonna     6      <unk>      <unk>

In [8]:
close_guesses = lib_nbest[lib_nbest.apply(lambda x: x.truth in x.hyp, axis=1)]
percent_right = 100 * len(close_guesses.truth.unique()) / len(lib_nbest.truth.unique())
print(f"{len(close_guesses)} included guesses; {round(percent_right,2)}% correct")
close_guesses

208 included guesses; 29.44% correct

        idx  beam               hyp  truth
10      And     0               AND    AND
11      And     1            AND AT    AND
12      And     2           AND END    AND
13      And     3           AND ALL    AND
14      And     4            AND IN    AND
...     ...   ...               ...    ...
1986    Let     6            LET US    LET
1987    Let     7           LET HIS    LET
1988    Let     8  LET YOU KNIT LET    LET
1989    Let     9           LET YOU    LET
1996  Gonna     6             <unk>  <unk>

[208 rows x 4 columns]

<a id='LibriSpeech_CTC_on_GigaSpeech200'></a>

[Top](#top)
___
### LibriSpeech CTC model on GigaSpeech 200 words

This model was trained on the Librispeech clean 100hr set using connectionist temporal classification instead of the encoder with attention method. This model's word error was 30% on the librispeech clean dev set.

In [9]:
path = '../result/lib_ctc_single_word_early/single_word_decode_test_output.csv' # test and dev are same set here 
cdf = pd.read_csv(path, sep='\t')

Looking at correct single word guesses:

In [10]:
good_guesses = len(cdf[cdf['hyp'] == cdf['truth']]) 
percent_right = 100 * good_guesses / len(cdf)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
cdf[cdf['hyp'] == cdf['truth']]

18 exact guesses; 9.0% correct

     idx     hyp   truth
1      1     AND     AND
13    13      SO      SO
25    25     NOT     NOT
27    27    LIKE    LIKE
28    28    WHAT    WHAT
36    36      IF      IF
43    43    YOUR    YOUR
46    46      ME      ME
51    51   WHICH   WHICH
74    74      NO      NO
98    98   <unk>   <unk>
102  102   FIRST   FIRST
124  124    LOOK    LOOK
128  128  BEFORE  BEFORE
131  131   GREAT   GREAT
157  157    PART    PART
163  163    SUCH    SUCH
185  185    DONE    DONE

Examples of bad guesses

In [11]:
cdf[cdf['hyp'] != cdf['truth']].head(50)

    idx          hyp   truth
0     0           UP     THE
2     2          TIP      TO
3     3          AND      OF
4     4           IT       A
5     5      THAT UP    THAT
6     6          AND      IN
7     7          BUT       I
8     8          YET     YOU
9     9           AS      IS
10   10         IT'S      IT
11   11         WHAT     WAS
12   12        <unk>     FOR
14   14           IN    THIS
15   15  RIGHT IT IT      WE
16   16        NOT A     BUT
17   17        WHERE    WITH
18   18         GOOD      ON
19   19          HAS    HAVE
20   20          PUT      HE
21   21         ELSE      AS
22   22           AN      BE
23   23        <unk>     ARE
24   24         LIKE    THEY
26   26           ET      AT
29   29           NO    KNOW
30   30            I     HIS
31   31        BUILT     ALL
32   32          NOT   ABOUT
33   33        WHITE     ONE
34   34         WORK      OR
35   35           GO     HAD
37   37          NOT      MY
38   38          ILL      DO
39   39           AN    FROM
40   40       IF ARE   THERE
41   41        <unk>    JUST
42   42        <unk>     CAN
44   44        <unk>      BY
45   45                   AH
47   47          BUT      AN
48   48         WENT    WHEN
49   49         WHAT    WERE
50   50    GENTLEMAN  PEOPLE
52   52          PUT     HER
53   53       SHOULD     SHE
54   54        DON'T     OUT
55   55       PICKED   THINK
56   56         LIKE   WOULD
57   57        <unk>      UP
58   58           AN    THEN

<a id='GigaSpeech_on_GigaSpeech200'></a>

[Top](#top)
___
### GigaSpeech Model performance on top 200 GigaSpeech words

*this is a mid-training checkpoint, not fully trained!!*

In [12]:
# path = '../results/gigaspeech_single_word_early/single_word_decode_test_output.csv' # test and dev are same set here 
# path = '../result/gigaspeech_word_45_wer/single_word_decode_dev_output.csv'
path = '../result/gigaspeech_single_word_decode_dev_output.csv'
gdf = pd.read_csv(path, sep='\t')

In [13]:
gdf.rename(columns={'idx': 'freq_rank'}, inplace=True)

Good guesses by model

In [14]:
good_guesses = len(gdf[gdf['hyp'] == gdf['truth']]) 
percent_right = 100 * good_guesses / len(gdf)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
gdf[gdf['hyp'] == gdf['truth']]

39 exact guesses; 19.5% correct

     freq_rank        hyp      truth
1            1        AND        AND
2            2         TO         TO
5            5       THAT       THAT
8            8        YOU        YOU
13          13         SO         SO
17          17       WITH       WITH
19          19       HAVE       HAVE
27          27       LIKE       LIKE
34          34         OR         OR
39          39       FROM       FROM
41          41       JUST       JUST
48          48       WHEN       WHEN
64          64        NOW        NOW
67          67       VERY       VERY
73          73     REALLY     REALLY
82          82      RIGHT      RIGHT
83          83       HERE       HERE
84          84         GO         GO
86          86       WELL       WELL
90          90      WHERE      WHERE
97          97     THINGS     THINGS
98          98       YEAH       YEAH
100        100       MUCH       MUCH
102        102      FIRST      FIRST
110        110  SOMETHING  SOMETHING
135        135      AGAIN      AGAIN
144        144      EVERY      EVERY
146        146      STILL      STILL
150        150       SAME       SAME
155        155     AROUND     AROUND
156        156       LAST       LAST
157        157       PART       PART
163        163       SUCH       SUCH
165        165     ALWAYS     ALWAYS
169        169        YES        YES
173        173       TELL       TELL
190        190     COURSE     COURSE
192        192       OKAY       OKAY
197        197       SURE       SURE

Examples of bad guesses

In [15]:
gdf[gdf['hyp'] != gdf['truth']].head(50)

    freq_rank       hyp   truth
0           0  YOU KNOW     THE
3           3       AND      OF
4           4       HEY       A
6           6       AND      IN
7           7        OH       I
9           9       AND      IS
10         10       AND      IT
11         11      WHAT     WAS
12         12        SO     FOR
14         14       YES    THIS
15         15     RIGHT      WE
16         16      BACK     BUT
18         18     RIGHT      ON
20         20        SO      HE
21         21       AND      AS
22         22      WELL      BE
23         23     THERE     ARE
24         24     RIGHT    THEY
25         25      YEAH     NOT
26         26     <unk>      AT
28         28       BUT    WHAT
29         29        NO    KNOW
30         30     <unk>     HIS
31         31        SO     ALL
32         32       AND   ABOUT
33         33       BUT     ONE
35         35        OH     HAD
36         36     <unk>      IF
37         37     NIGHT      MY
38         38      BILL      DO
40         40       BUT   THERE
42         42      OKAY     CAN
43         43   YOU ARE    YOUR
44         44        OH      BY
45         45      YEAH      AH
46         46        NO      ME
47         47       AND      AN
49         49      WORK    WERE
50         50  YOU KNOW  PEOPLE
51         51      MUCH   WHICH
52         52     <unk>     HER
53         53        SO     SHE
54         54        AT     OUT
55         55     THICK   THINK
56         56      LIKE   WOULD
57         57       BUT      UP
58         58       AND    THEN
59         59    REALLY     OUR
60         60       HOW     WHO
61         61       BUT   THEIR

<a id='GigaSpeech_on_EnglishCCC'></a>

[Top](#top)
___
### GigaSpeech Model performance on top EnglishCCC words


Some of the target words of the English Consistent Confusion Corpus words are out of the GigaSpeech vocabulary, so we will only look at words the model knows.

In [16]:
path = '../result/english_ccc_single_word_decode_test_output.csv'
ecccdf = pd.read_csv(path, sep='\t')

In [17]:
len(ecccdf)

3207

Looking at correct single word guesses:

In [18]:
good_guesses = ecccdf[(ecccdf['hyp'] == ecccdf['truth']) &  (ecccdf['truth'] != '<unk>')]
percent_right = 100 * len(good_guesses) / len(ecccdf)
print(f"{len(good_guesses)} exact guesses; {round(percent_right,2)}% correct")
good_guesses

581 exact guesses; 18.12% correct

       idx       hyp     truth
4        4   BECAUSE   BECAUSE
10      10      FAME      FAME
16      16  RECEIVED  RECEIVED
19      19   HEARING   HEARING
23      23     CLASS     CLASS
...    ...       ...       ...
3186  3186    CRISIS    CRISIS
3190  3190     VISIT     VISIT
3196  3196      LIKE      LIKE
3198  3198     SORRY     SORRY
3199  3199       DAD       DAD

[581 rows x 3 columns]

Examples of incorrect guesses

In [19]:
ecccdf[(ecccdf['hyp'] != ecccdf['truth']) &  (ecccdf['truth'] != '<unk>')].head(50)

    idx        hyp      truth
2     2      <unk>     STANCE
3     3      <unk>     REMOTE
6     6     INSIDE    INSIGHT
7     7      <unk>     RADIUS
11   11    A <unk>      ACUTE
12   12   CHILDREN   CHILDISH
13   13         BY      BUYER
14   14      <unk>      GUEST
15   15      <unk>       DRUG
17   17       MARK     MARKED
18   18     FORMER     FORMAL
20   20      <unk>    CAUTION
22   22      <unk>      CHESS
24   24     GROWTH      GROSS
25   25      <unk>     HUMBLE
26   26       MEET       NEAT
30   30      <unk>        JAW
32   32      <unk>    SAILING
33   33      <unk>      NAVAL
34   34      <unk>     PATROL
36   36      <unk>      CHESS
37   37      <unk>      FAIRY
41   41      <unk>       JUNK
44   44       HERE        ERA
45   45       PUSH     PUSHED
46   46       THAT       BOAT
47   47                  HOOK
48   48      <unk>  MOONLIGHT
49   49  THE <unk>       GENE
53   53      <unk>        HUT
55   55      <unk>       PINE
57   57      <unk>      COUGH
58   58      <unk>     POWDER
59   59      <unk>      ASSET
60   60       HERE       HAIR
61   61      <unk>      CLOTH
62   62      <unk>     WOODEN
63   63       PLAY       PLEA
65   65      FIRST    FIRSTLY
66   66      <unk>      CHARM
70   70        FAT       THAT
71   71        SHE      CHEEK
72   72      <unk>       ROAR
73   73        AND       EARN
74   74      <unk>     CALMLY
75   75        BUT       WHAT
76   76      <unk>      FRAUD
77   77   KILL HER     KILLER
78   78       FIVE       BITE
80   80      <unk>     SELDOM

<a id='GigaSpeech_Top_10'></a>

[Top](#top) 
___

## GigaSpeech Top 10 Decode

In [20]:
path = '../result/gigaspeech_single_word_top_N_dev_beam-10-0.csv'
top_10 = pd.read_csv(path, sep='\t')

In [21]:
top_10

        idx  beam          hyp  truth
0       The     0    <unk> NOT    THE
1       The     1     YOU KNOW    THE
2       The     2  YOU THOUGHT    THE
3       The     3    YOU <unk>    THE
4       The     4          NOT    THE
...     ...   ...          ...    ...
1995  Gonna     5          OUT  GONNA
1996  Gonna     6        RIGHT  GONNA
1997  Gonna     7      IT YEAH  GONNA
1998  Gonna     8           IT  GONNA
1999  Gonna     9       AN APP  GONNA

[2000 rows x 4 columns]

In [22]:
good_guesses = top_10[(top_10['hyp'] == top_10['truth']) & (top_10['beam']==0)]
percent_right = 100 * len(good_guesses) / len(top_10.truth.unique())
print(f"{len(good_guesses)} exact guesses; {round(percent_right,2)}% correct")
good_guesses

41 exact guesses; 20.5% correct

            idx  beam        hyp      truth
10          And     0        AND        AND
20           To     0         TO         TO
50         That     0       THAT       THAT
80          You     0        YOU        YOU
130          So     0         SO         SO
160         But     0        BUT        BUT
170        With     0       WITH       WITH
190        Have     0       HAVE       HAVE
270        Like     0       LIKE       LIKE
280        What     0       WHAT       WHAT
340          Or     0         OR         OR
390        From     0       FROM       FROM
410        Just     0       JUST       JUST
480        When     0       WHEN       WHEN
640         Now     0        NOW        NOW
670        Very     0       VERY       VERY
730      Really     0     REALLY     REALLY
820       Right     0      RIGHT      RIGHT
830        Here     0       HERE       HERE
840          Go     0         GO         GO
860        Well     0       WELL       WELL
900       Where     0      WHERE      WHERE
970      Things     0     THINGS     THINGS
980        Yeah     0       YEAH       YEAH
1000       Much     0       MUCH       MUCH
1020      First     0      FIRST      FIRST
1100  Something     0  SOMETHING  SOMETHING
1350      Again     0      AGAIN      AGAIN
1440      Every     0      EVERY      EVERY
1460      Still     0      STILL      STILL
1500       Same     0       SAME       SAME
1550     Around     0     AROUND     AROUND
1560       Last     0       LAST       LAST
1570       Part     0       PART       PART
1630       Such     0       SUCH       SUCH
1650     Always     0     ALWAYS     ALWAYS
1690        Yes     0        YES        YES
1730       Tell     0       TELL       TELL
1900     Course     0     COURSE     COURSE
1920       Okay     0       OKAY       OKAY
1970       Sure     0       SURE       SURE

In [23]:
top_match_guesses = top_10[(top_10['hyp'] == top_10['truth'])]
percent_right = 100 * len(top_match_guesses) / len(top_10.truth.unique())
print(f"{len(top_match_guesses)} matched guesses; {round(percent_right,2)}% correct")
top_match_guesses

89 matched guesses; 44.5% correct

         idx  beam     hyp   truth
10       And     0     AND     AND
20        To     0      TO      TO
50      That     0    THAT    THAT
61        In     1      IN      IN
80       You     0     YOU     YOU
...      ...   ...     ...     ...
1867    Away     7    AWAY    AWAY
1900  Course     0  COURSE  COURSE
1916  Better     6  BETTER  BETTER
1920    Okay     0    OKAY    OKAY
1970    Sure     0    SURE    SURE

[89 rows x 4 columns]

In [24]:
len(close_guesses.truth.unique())

58