In [1]:
import pandas as pd 
import numpy as np

In [2]:
# Get gigaspeech word order:

with open('../corpus/gigaspeech_top_200.txt','r') as txt:
    words = txt.read().splitlines()
    word_map = {word:ix for ix, word in enumerate(words)}

### Look at Librispeech model performance on top 200 Gigaspeech words

In [7]:
path = '../result/single_word_decode_test_output.csv' # test and dev are same set here 
df = pd.read_csv(path, sep='\t')

In [66]:
good_guesses = len(df[df['hyp'] == df['truth']]) 
percent_right = good_guesses / len(df)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
df[df['hyp'] == df['truth']]

12 exact guesses; 0.06% correct

     idx    hyp  truth
1      1    AND    AND
28    28   WHAT   WHAT
36    36     IF     IF
51    51  WHICH  WHICH
64    64    NOW    NOW
74    74     NO     NO
98    98  <unk>  <unk>
124  124   LOOK   LOOK
144  144  EVERY  EVERY
163  163   SUCH   SUCH
164  164   FIND   FIND
198  198    LET    LET

In [11]:
len(df[df['hyp'] == df['truth']]) / len(df)

0.06

In [25]:
df[df['hyp'] == df['truth']]

12

In [70]:
df[df['hyp'] != df['truth']].head(50)

    idx                                  hyp   truth
0     0                               IT YET     THE
2     2                                <unk>      TO
3     3                                   AS      OF
4     4                                            A
5     5                             BUT THAT    THAT
6     6                                           IN
7     7                                <unk>       I
8     8                                   YO     YOU
9     9                                 IT'S      IS
10   10                                 IT'S      IT
11   11                               WHAT'S     WAS
12   12                              FLORIDA     FOR
13   13                               ITSELF      SO
14   14                                         THIS
15   15                                <unk>      WE
16   16                                  NOT     BUT
17   17                              WOULDST    WITH
18   18                                  BUT      ON
19   19                             CAN'T MY    HAVE
20   20                                           HE
21   21                                 IT'S      AS
22   22                                ABOUT      BE
23   23                                EARTH     ARE
24   24                                 THAT    THEY
25   25                                  YET     NOT
26   26                                 THEN      AT
27   27                                  LET    LIKE
29   29                                   NO    KNOW
30   30                                   AS     HIS
31   31                            CAN'T GET     ALL
32   32                              AND NOT   ABOUT
33   33                                 WHAT     ONE
34   34                            THE <unk>      OR
35   35                                <unk>     HAD
37   37                              NOT NOT      MY
38   38                                DON'T      DO
39   39                                SPENT    FROM
40   40                                 THAT   THERE
41   41                                  GAS    JUST
42   42                                 DEAD     CAN
43   43                               YOU'RE    YOUR
44   44                          NIGHT NIGHT      BY
45   45                                   IF      AH
46   46                                 NOTE      ME
47   47                                  AND      AN
48   48                                 WENT    WHEN
49   49                          <unk> <unk>    WERE
50   50                          DON'T DON'T  PEOPLE
52   52                                  PIT     HER
53   53  COULDN'T COULDN'T COULDN'T COULDN'T     SHE

### LibriSpeech CTC model on GigaSpeech 200 words

In [63]:
path = '../result/lib_ctc_single_word_early/single_word_decode_test_output.csv' # test and dev are same set here 
cdf = pd.read_csv(path, sep='\t')

In [65]:
good_guesses = len(cdf[cdf['hyp'] == cdf['truth']]) 
percent_right = good_guesses / len(cdf)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
cdf[cdf['hyp'] == cdf['truth']]

18 exact guesses; 0.09% correct

     idx     hyp   truth
1      1     AND     AND
13    13      SO      SO
25    25     NOT     NOT
27    27    LIKE    LIKE
28    28    WHAT    WHAT
36    36      IF      IF
43    43    YOUR    YOUR
46    46      ME      ME
51    51   WHICH   WHICH
74    74      NO      NO
98    98   <unk>   <unk>
102  102   FIRST   FIRST
124  124    LOOK    LOOK
128  128  BEFORE  BEFORE
131  131   GREAT   GREAT
157  157    PART    PART
163  163    SUCH    SUCH
185  185    DONE    DONE

In [69]:
cdf[cdf['hyp'] != cdf['truth']].head(50)

    idx          hyp   truth
0     0           UP     THE
2     2          TIP      TO
3     3          AND      OF
4     4           IT       A
5     5      THAT UP    THAT
6     6          AND      IN
7     7          BUT       I
8     8          YET     YOU
9     9           AS      IS
10   10         IT'S      IT
11   11         WHAT     WAS
12   12        <unk>     FOR
14   14           IN    THIS
15   15  RIGHT IT IT      WE
16   16        NOT A     BUT
17   17        WHERE    WITH
18   18         GOOD      ON
19   19          HAS    HAVE
20   20          PUT      HE
21   21         ELSE      AS
22   22           AN      BE
23   23        <unk>     ARE
24   24         LIKE    THEY
26   26           ET      AT
29   29           NO    KNOW
30   30            I     HIS
31   31        BUILT     ALL
32   32          NOT   ABOUT
33   33        WHITE     ONE
34   34         WORK      OR
35   35           GO     HAD
37   37          NOT      MY
38   38          ILL      DO
39   39           AN    FROM
40   40       IF ARE   THERE
41   41        <unk>    JUST
42   42        <unk>     CAN
44   44        <unk>      BY
45   45                   AH
47   47          BUT      AN
48   48         WENT    WHEN
49   49         WHAT    WERE
50   50    GENTLEMAN  PEOPLE
52   52          PUT     HER
53   53       SHOULD     SHE
54   54        DON'T     OUT
55   55       PICKED   THINK
56   56         LIKE   WOULD
57   57        <unk>      UP
58   58           AN    THEN

### GigaSpeech Model performance on top 200 GigaSpeech words

*this is a mid-training checkpoint, not fully trained!!*

In [3]:
# path = '../results/gigaspeech_single_word_early/single_word_decode_test_output.csv' # test and dev are same set here 
path = '../result/gigaspeech_word_45_wer/single_word_decode_dev_output.csv'
gdf = pd.read_csv(path, sep='\t')

In [4]:
gdf.rename(columns={'idx': 'freq_rank'}, inplace=True)

In [5]:
good_guesses = len(gdf[gdf['hyp'] == gdf['truth']]) 
percent_right = good_guesses / len(gdf)
print(f"{good_guesses} exact guesses; {round(percent_right,2)}% correct")
gdf[gdf['hyp'] == gdf['truth']]

57 exact guesses; 0.28% correct

     freq_rank        hyp      truth
1            1        AND        AND
2            2         TO         TO
8            8        YOU        YOU
10          10         IT         IT
13          13         SO         SO
14          14       THIS       THIS
15          15         WE         WE
16          16        BUT        BUT
27          27       LIKE       LIKE
28          28       WHAT       WHAT
33          33        ONE        ONE
34          34         OR         OR
38          38         DO         DO
39          39       FROM       FROM
40          40      THERE      THERE
41          41       JUST       JUST
43          43       YOUR       YOUR
46          46         ME         ME
48          48       WHEN       WHEN
51          51      WHICH      WHICH
52          52        HER        HER
58          58       THEN       THEN
64          64        NOW        NOW
66          66        HOW        HOW
68          68    BECAUSE    BECAUSE
73          73     REALLY     REALLY
82          82      RIGHT      RIGHT
83          83       HERE       HERE
86          86       WELL       WELL
87          87        SEE        SEE
90          90      WHERE      WHERE
96          96        SAY        SAY
98          98       YEAH       YEAH
102        102      FIRST      FIRST
110        110  SOMETHING  SOMETHING
116        116       DOWN       DOWN
122        122    THROUGH    THROUGH
128        128     BEFORE     BEFORE
134        134        WHY        WHY
135        135      AGAIN      AGAIN
138        138        DAY        DAY
146        146      STILL      STILL
157        157       PART       PART
163        163       SUCH       SUCH
165        165     ALWAYS     ALWAYS
166        166       DOES       DOES
168        168       NEXT       NEXT
169        169        YES        YES
170        170      POINT      POINT
172        172       SORT       SORT
186        186       AWAY       AWAY
188        188   QUESTION   QUESTION
189        189       FEEL       FEEL
192        192       OKAY       OKAY
193        193      WHILE      WHILE
196        196       EACH       EACH
197        197       SURE       SURE

In [6]:
gdf[gdf['hyp'] != gdf['truth']].head(50)

    freq_rank        hyp   truth
0           0      <unk>     THE
3           3        AND      OF
4           4      <unk>       A
5           5        BUT    THAT
6           6        AND      IN
7           7         OH       I
9           9                 IS
11         11        WHY     WAS
12         12         SO     FOR
17         17        WAS    WITH
18         18       FIND      ON
19         19        HAS    HAVE
20         20        SEE      HE
21         21                 AS
22         22        DAY      BE
23         23      THERE     ARE
24         24       OKAY    THEY
25         25       YEAH     NOT
26         26        AND      AT
29         29         NO    KNOW
30         30    BECAUSE     HIS
31         31        BUT     ALL
32         32        NOW   ABOUT
35         35        HOW     HAD
36         36                 IF
37         37        NOW      MY
42         42       OKAY     CAN
44         44       WELL      BY
45         45        BUT      AH
47         47        BUT      AN
49         49       WHAT    WERE
50         50   GIVE YOU  PEOPLE
53         53        SAY     SHE
54         54         IT     OUT
55         55  THANK YOU   THINK
56         56       WHAT   WOULD
57         57                 UP
59         59      THERE     OUR
60         60      <unk>     WHO
61         61      THERE   THEIR
62         62       THEN    THEM
63         63      NORTH    MORE
65         65       SAID    SOME
67         67        NOW    VERY
69         69       WELL    WILL
70         70       THEN    BEEN
71         71        AND      UM
72         72        AND   GOING
74         74       WELL      NO
75         75       OKAY    TIME